name: study_scheduler
description: Simple study timetable generator for students.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

 
  
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

  # Notifications
  flutter_local_notifications: ^19.2.1

  # State Management
  flutter_riverpod: ^2.5.1
  permission_handler: ^12.0.1

  # Time
  intl: ^0.20.2
  timezone: ^0.10.0 

  # UI/UX
  flutter_colorpicker: ^1.1.0
  
  flutter_timezone: ^4.1.1

  # UI
  table_calendar: ^3.1.2
  go_router: ^16.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

 
  flutter_lints: ^6.0.0


flutter:

  
  uses-material-design: true

  
